module.exports = {
  data: {
    players: {
      "Brayan Cortés": {
        name: "Brayan Cortés",
        number: 1,
        age: 29,
        height: 1.85,
        weight: 87,
        nationality: "Chile",
      },
      "Eduardo Villanueva": {
        name: "Eduardo Villanueva",
        number: 12,
        age: 19,
        height: 1.88,
        weight: 76,
        nationality: "Chile",
      },
      "Fernando de Paul": {
        name: "Fernando de Paul",
        number: 30,
        age: 32,
        height: 1.83,
        weight: 83,
        nationality: "Chile",
      },
      "Omar Carabali": {
        name: "Omar Carabali",
        number: 31,
        age: 26,
        height: 1.88,
        weight: 83,
        nationality: "Chile",
      },
      "Jeyson Rojas": {
        name: "Jeyson Rojas",
        number: 2,
        age: 22,
        height: 1.85,
        weight: 73,
        nationality: "Chile",
      },
      "Daniel Gutiérrez": {
        name: "Daniel Gutiérrez",
        number: 3,
        age: 21,
        height: 1.8,
        weight: 68,
        nationality: "Chile",
      },
      "Alan Saldivia": {
        name: "Alan Saldivia",
        number: 4,
        age: 22,
        height: 1.8,
        weight: 78,
        nationality: "Uruguay",
      },
      "Bruno Gutiérrez": {
        name: "Bruno Gutiérrez",
        number: 13,
        age: 21,
        height: 1.83,
        weight: 68,
        nationality: "Chile",
      },
      "Emiliano Amor": {
        name: "Emiliano Amor",
        number: 15,
        age: 28,
        height: 1.91,
        weight: 78,
        nationality: "Argentina",
      },
      "Oscar Opazo": {
        name: "Oscar Opazo",
        number: 16,
        age: 33,
        height: 1.7,
        weight: 68,
        nationality: "Chile",
      },
      "Erick Wiemberg": {
        name: "Erick Wiemberg",
        number: 21,
        age: 29,
        height: 1.78,
        weight: 67,
        nationality: "Chile",
      },
      "Ramiro González": {
        name: "Ramiro González",
        number: 33,
        age: 33,
        height: 1.85,
        weight: 82,
        nationality: "Argentina",
      },
      "Matias Pinto": {
        name: "Matias Pinto",
        number: 35,
        age: 19,
        height: 1.75,
        weight: 67,
        nationality: "Chile",
      },
      "Miguel Toledo": {
        name: "Miguel Toledo",
        number: 38,
        age: 20,
        height: 1.85,
        weight: 76,
        nationality: "Chile",
      },
      "Maximiliano Falcón": {
        name: "Maximiliano Falcón",
        number: 37,
        age: 26,
        height: 1.78,
        weight: 78,
        nationality: "Uruguay",
      },
      "Nicolás Suárez": {
        name: "Nicolás Suárez",
        number: 38,
        age: 18,
        height: 1.8,
        weight: 72,
        nationality: "Chile",
      },
      "Leonardo Gil": {
        name: "Leonardo Gil",
        number: 5,
        age: 32,
        height: 1.75,
        weight: 66,
        nationality: "Chile",
      },
      "Cesar Fuentes": {
        name: "Cesar Fuentes",
        number: 6,
        age: 30,
        height: 1.73,
        weight: 68,
        nationality: "Chile",
      },
      "Carlos Palacios": {
        name: "Carlos Palacios",
        number: 7,
        age: 23,
        height: 1.83,
        weight: 78,
        nationality: "Chile",
      },
      "Esteban Pavez": {
        name: "Esteban Pavez",
        number: 8,
        age: 33,
        height: 1.8,
        weight: 76,
        nationality: "Chile",
      },
      "Pablo Parra": {
        name: "Pablo Parra",
        number: 10,
        age: 29,
        height: 1.78,
        weight: 58,
        nationality: "Chile",
      },
      "Ignacio Jara": {
        name: "Ignacio Jara",
        number: 17,
        age: 27,
        height: 1.68,
        weight: 73,
        nationality: "Chile",
      },
      "Bastian Silva": {
        name: "Bastian Silva",
        number: 18,
        age: 20,
        height: "Chile",
        weight: null,
        nationality: null,
      },
      "Gonzalo Castellani": {
        name: "Gonzalo Castellani",
        number: 19,
        age: 36,
        height: 1.85,
        weight: 82,
        nationality: "Argentina",
      },
      "Alexander Oraz": {
        name: "Alexander Oraz",
        number: 20,
        age: 21,
        height: 1.73,
        weight: 62,
        nationality: "Chile",
      },
      "Arturo Vidal": {
        name: "Arturo Vidal",
        number: 23,
        age: 36,
        height: 1.8,
        weight: 73,
        nationality: "Chile",
      },
      "Leandro Hernández": {
        name: "Leandro Hernández",
        number: 24,
        age: 18,
        height: 1.68,
        weight: null,
        nationality: "Chile",
      },
      "Dylan Porilla": {
        name: "Dylan Porilla",
        number: 25,
        age: 20,
        height: 1.75,
        weight: 68,
        nationality: "Chile",
      },
      "Matias Moya": {
        name: "Matias Moya",
        number: 28,
        age: 26,
        height: 1.7,
        weight: 63,
        nationality: "Argentina",
      },
      "Lucas Soto": {
        name: "Lucas Soto",
        number: 28,
        age: 21,
        height: 1.83,
        weight: 62,
        nationality: "Chile",
      },
      "Lucas Cepeda": {
        name: "Lucas Cepeda",
        number: 32,
        age: 21,
        height: 1.78,
        weight: 66,
        nationality: "Chile",
      },
      "Vicente Pizarro": {
        name: "Vicente Pizarro",
        number: 34,
        age: 21,
        height: 1.73,
        weight: 68,
        nationality: "Chile",
      },
      "Francisco Rivera": {
        name: "Francisco Rivera",
        number: 39,
        age: 23,
        height: 1.78,
        weight: 66,
        nationality: "España",
      },
      "Damián Pizarro": {
        name: "Damián Pizarro",
        number: 9,
        age: 19,
        height: 1.88,
        weight: 83,
        nationality: "Chile",
      },
      "Marco Bolados": {
        name: "Marco Bolados",
        number: 11,
        age: 28,
        height: 1.73,
        weight: 63,
        nationality: "Chile",
      },
      "Cristian Zavala": {
        name: "Cristian Zavala",
        number: 14,
        age: 24,
        height: 1.7,
        weight: null,
        nationality: "Chile",
      },
      "Leandro Benegas": {
        name: "Leandro Benegas",
        number: 22,
        age: 35,
        height: 1.8,
        weight: 86,
        nationality: "Chile",
      },
      "Guillermo Paiva": {
        name: "Guillermo Paiva",
        number: 29,
        age: 26,
        height: 1.8,
        weight: 78,
        nationality: "Paraguay",
      },
    },
  colo_colo: {
    name: "Colo-Colo",
    country: "chile",
    stadium: "Estadio Monumental",
    founder: "David Arellano",
    "foundation-date": "4/04/1925",
    "national-leagues": "33",
    "chile-cup": "14",
    "super-cup": "3",
    "liberators-cup": "1",
  },
  }
};
